import type { ScenarioDefinition } from "../runner";

export const factorScenarios: ScenarioDefinition[] = [
  {
    id: "factor-normal-production",
    name: "Normal Production",
    summary: "Progressive output gains with stable quality and stage advancement.",
    initialPayload: {
      currentStage: "TURNING",
      machineUtilization: 0.82,
      qualityPassRate: 0.992,
      qualityRejectCount: 3,
      quantityPlanned: 12000,
      quantityProduced: 600,
      shiftsCompleted: 1,
    },
    steps: [
      {
        id: "factor-normal-1",
        title: "Ramp turning output",
        description: "Push a healthy production update from the turning line.",
        delayMs: 4000,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          machineUtilization: 0.84,
          qualityPassRate: 0.993,
          quantityProduced: 1200,
          shiftsCompleted: 2,
        },
      },
      {
        id: "factor-normal-2",
        title: "Second shift closes",
        description: "Advance throughput while keeping rejects low.",
        delayMs: 4000,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          qualityPassRate: 0.991,
          quantityProduced: 2400,
          shiftsCompleted: 3,
        },
      },
      {
        id: "factor-normal-3",
        title: "Move into heat treatment",
        description: "Switch stages as the production batch reaches the next operation.",
        delayMs: 5000,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          currentStage: "HEAT_TREATMENT",
          machineUtilization: 0.86,
          qualityPassRate: 0.989,
          quantityProduced: 4800,
        },
      },
    ],
  },
  {
    id: "factor-quality-failure",
    name: "Quality Failure",
    summary: "A steady run degrades into a high-severity quality threshold issue.",
    initialPayload: {
      currentStage: "TURNING",
      machineUtilization: 0.79,
      qualityPassRate: 0.991,
      qualityRejectCount: 4,
      quantityPlanned: 12000,
      quantityProduced: 1000,
      shiftsCompleted: 2,
    },
    steps: [
      {
        id: "factor-quality-1",
        title: "Rejects begin rising",
        description: "Early warning signs show up before the threshold is breached.",
        delayMs: 3500,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          qualityPassRate: 0.978,
          qualityRejectCount: 10,
          quantityProduced: 1800,
        },
      },
      {
        id: "factor-quality-2",
        title: "Threshold breach",
        description: "Push a quality event with a sharp pass-rate drop.",
        delayMs: 5000,
        updateType: "QUALITY_EVENT",
        payload: {
          machineUtilization: 0.71,
          qualityPassRate: 0.81,
          qualityRejectCount: 36,
          quantityProduced: 2200,
        },
      },
      {
        id: "factor-quality-3",
        title: "Containment run",
        description: "Production continues while quality remains below target.",
        delayMs: 3500,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          qualityPassRate: 0.83,
          qualityRejectCount: 44,
          quantityProduced: 2600,
        },
      },
    ],
  },
  {
    id: "factor-production-delay",
    name: "Production Delay",
    summary: "Output slows and utilization dips, setting up a delayed delivery trajectory.",
    initialPayload: {
      currentStage: "TURNING",
      machineUtilization: 0.64,
      qualityPassRate: 0.988,
      qualityRejectCount: 8,
      quantityPlanned: 12000,
      quantityProduced: 400,
      shiftsCompleted: 1,
    },
    steps: [
      {
        id: "factor-delay-1",
        title: "Under target output",
        description: "The line misses expected throughput for the current interval.",
        delayMs: 4500,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          machineUtilization: 0.58,
          quantityProduced: 650,
        },
      },
      {
        id: "factor-delay-2",
        title: "Recovery stalls",
        description: "Reject count grows while utilization continues to slip.",
        delayMs: 4500,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          machineUtilization: 0.55,
          qualityRejectCount: 14,
          quantityProduced: 900,
        },
      },
      {
        id: "factor-delay-3",
        title: "Delay pattern holds",
        description: "A third slow update reinforces the delayed pattern.",
        delayMs: 5000,
        updateType: "PRODUCTION_UPDATE",
        payload: {
          machineUtilization: 0.51,
          qualityPassRate: 0.981,
          quantityProduced: 1100,
        },
      },
    ],
  },
];
